{% set name = "geo-skeletons" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geo_skeletons-{{ version }}.tar.gz
  sha256: cc8b437f8c738a85496f434d3e14a8a431cee3abb1b58bc630ff9140d7646851

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - flit
  run:
    - python >=3.9
    - numpy
    - pandas
    - xarray
    - utm
    - geopy

test:
  imports:
    - geo_skeletons
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/bjorkqvi/skeletons
  summary: Easily extended way to represent structured and unstructured geophysical data.
  description: Easily extended way to represent structured and unstructured geophysical data.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://https://data-skeletons.readthedocs.io/
  dev_url: https://github.com/bjorkqvi/skeletons

extra:
  recipe-maintainers:
    - bjorkqvi
