{% set name = "geo-skeletons" %}
{% set version = "0.20.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geo_skeletons-{{ version }}.tar.gz
  sha256: 78031a7648e9f1d98e2399855dee9219c106a399a34553382148e30df86321ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - flit
  run:
    - python >={{ python_min }},<3.12
    - numpy
    - pandas
    - xarray
    - utm
    - geopy
    - dask
    - scipy
    - geo-parameters >=0.9.4

test:
  imports:
    - geo_skeletons
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/bjorkqvi/skeletons
  summary: Easily extended way to represent structured and unstructured geophysical data.
  description: Easily extended way to represent structured and unstructured geophysical data.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://https://data-skeletons.readthedocs.io/
  dev_url: https://github.com/bjorkqvi/skeletons

extra:
  recipe-maintainers:
    - bjorkqvi
