{% set name = "geo-skeletons" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geo_skeletons-{{ version }}.tar.gz
  sha256: 30a17a757d035ed90688c2f3f91d7ba3fe0643846309452a4e888839bd2b87b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<=3.13
    - pip
    - setuptools
    - flit
  run:
    - python >=3.9,<=3.13
    - numpy
    - pandas
    - xarray
    - utm
    - geopy
    - dask
    - scipy
    - geo-parameters >=0.10.0

test:
  imports:
    - geo_skeletons
  requires:
    - pip
    - python 3.9
  commands:
    - pip check

about:
  home: https://github.com/bjorkqvi/skeletons
  summary: Easily extended way to represent structured and unstructured geophysical data.
  description: Easily extended way to represent structured and unstructured geophysical data.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://https://data-skeletons.readthedocs.io/
  dev_url: https://github.com/bjorkqvi/skeletons

extra:
  recipe-maintainers:
    - bjorkqvi
