{% set name = "geo-skeletons" %}
{% set version = "0.9.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geo_skeletons-{{ version }}.tar.gz
  sha256: c7b41d105b98c04089c0d51c830ef235796d30ba4b4dbc3c001ef33aa71e32ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - flit
  run:
    - python >=3.9
    - numpy
    - pandas
    - xarray
    - utm
    - geopy

test:
  imports:
    - geo_skeletons
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/bjorkqvi/skeletons
  summary: Easily extended way to represent structured and unstructured geophysical data.
  description: Easily extended way to represent structured and unstructured geophysical data.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://https://data-skeletons.readthedocs.io/
  dev_url: https://github.com/bjorkqvi/skeletons

extra:
  recipe-maintainers:
    - bjorkqvi
